; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
debug_tool = esp-prog

[env:upesy_wroom_WEB]
build_flags = -D WEB
lib_deps = 
	adafruit/Adafruit AHTX0@^2.0.6
	adafruit/Adafruit BMP280 Library@^3.0.0
	robtillaart/I2C_LCD@^0.2.6

[env:upesy_wroom_LCD]
build_flags = -D LCD
lib_deps = 
	adafruit/Adafruit AHTX0@^2.0.6
	adafruit/Adafruit BMP280 Library@^3.0.0
	robtillaart/I2C_LCD@^0.2.6

[env:upesy_wroom_BLE]
build_flags = -D USE_BLE
lib_deps = 
	adafruit/Adafruit AHTX0@^2.0.6
	adafruit/Adafruit BMP280 Library@^3.0.0
	robtillaart/I2C_LCD@^0.2.6
	sensirion/Sensirion Gadget BLE Arduino Lib@^1.5.0
	sensirion/Sensirion UPT Core@0.5.1
	h2zero/NimBLE-Arduino@^2.3.0

[env:upesy_wroom_compound]
build_flags = -D Compound
lib_deps = 
	adafruit/Adafruit AHTX0@^2.0.6
	adafruit/Adafruit BMP280 Library@^3.0.0
	robtillaart/I2C_LCD@^0.2.6
	sensirion/Sensirion Gadget BLE Arduino Lib@^1.5.0
	sensirion/Sensirion UPT Core@0.5.1
	h2zero/NimBLE-Arduino@^2.3.0
